sudo: false

language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - yarn global add yarn@latest
  - yarn

script:
  - yarn test
  - yarn prebuild
  - yarn build
  - yarn postbuild
