// flow-typed signature: 2a46dad8cc08865c54a4edc03f414bce
// flow-typed version: <<STUB>>/atmosphere.js_vhttps://github.com/Quiq/atmosphere-js/tarball/cf35c913143cf2c391b6bcb694ae8a47794a1b88/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atmosphere.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'atmosphere.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atmosphere.js/lib/atmosphere' {
  declare module.exports: any;
}

declare module 'atmosphere.js/lib/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atmosphere.js/index' {
  declare module.exports: $Exports<'atmosphere.js'>;
}
declare module 'atmosphere.js/index.js' {
  declare module.exports: $Exports<'atmosphere.js'>;
}
declare module 'atmosphere.js/lib/atmosphere.js' {
  declare module.exports: $Exports<'atmosphere.js/lib/atmosphere'>;
}
declare module 'atmosphere.js/lib/browser.js' {
  declare module.exports: $Exports<'atmosphere.js/lib/browser'>;
}
