// flow-typed signature: 96925d0407b270fb565186f349390fde
// flow-typed version: <<STUB>>/core-ui_vgit+ssh://git@gitlab.quiq.sh/development/core-ui.git#0.0.4/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'core-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'core-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'core-ui/interfaces/moment' {
  declare module.exports: any;
}

declare module 'core-ui/services/i18nService' {
  declare module.exports: any;
}

declare module 'core-ui/services/tests/i18nServiceSpec' {
  declare module.exports: any;
}

declare module 'core-ui/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'core-ui/interfaces/moment.js' {
  declare module.exports: $Exports<'core-ui/interfaces/moment'>;
}
declare module 'core-ui/services/i18nService.js' {
  declare module.exports: $Exports<'core-ui/services/i18nService'>;
}
declare module 'core-ui/services/tests/i18nServiceSpec.js' {
  declare module.exports: $Exports<'core-ui/services/tests/i18nServiceSpec'>;
}
declare module 'core-ui/types.js' {
  declare module.exports: $Exports<'core-ui/types'>;
}
