// flow-typed signature: 21712335d4203572d9ab082c291aba6d
// flow-typed version: <<STUB>>/emoji-mart_v2.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-mart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-mart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-mart/dist/components/anchors' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/category' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/emoji' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/picker' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/pickerSpec' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/preview' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/search' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/components/skins' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/data/data' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/data/index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/createClass' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/extends' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/inherits' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/objectGetPrototypeOf' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/possibleConstructorReturn' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/polyfills/stringFromCodePoint' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/svgs/index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/build-search' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/emoji-index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/emoji-indexSpec' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/frequently' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/index' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/utils/store' {
  declare module.exports: any;
}

declare module 'emoji-mart/dist/vendor/raf-polyfill' {
  declare module.exports: any;
}

declare module 'emoji-mart/stories/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-mart/dist/components/anchors.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/anchors'>;
}
declare module 'emoji-mart/dist/components/category.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/category'>;
}
declare module 'emoji-mart/dist/components/emoji.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/emoji'>;
}
declare module 'emoji-mart/dist/components/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/index'>;
}
declare module 'emoji-mart/dist/components/picker.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/picker'>;
}
declare module 'emoji-mart/dist/components/pickerSpec.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/pickerSpec'>;
}
declare module 'emoji-mart/dist/components/preview.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/preview'>;
}
declare module 'emoji-mart/dist/components/search.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/search'>;
}
declare module 'emoji-mart/dist/components/skins.js' {
  declare module.exports: $Exports<'emoji-mart/dist/components/skins'>;
}
declare module 'emoji-mart/dist/data/data.js' {
  declare module.exports: $Exports<'emoji-mart/dist/data/data'>;
}
declare module 'emoji-mart/dist/data/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/data/index'>;
}
declare module 'emoji-mart/dist/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/index'>;
}
declare module 'emoji-mart/dist/polyfills/createClass.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/createClass'>;
}
declare module 'emoji-mart/dist/polyfills/extends.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/extends'>;
}
declare module 'emoji-mart/dist/polyfills/inherits.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/inherits'>;
}
declare module 'emoji-mart/dist/polyfills/objectGetPrototypeOf.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/objectGetPrototypeOf'>;
}
declare module 'emoji-mart/dist/polyfills/possibleConstructorReturn.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/possibleConstructorReturn'>;
}
declare module 'emoji-mart/dist/polyfills/stringFromCodePoint.js' {
  declare module.exports: $Exports<'emoji-mart/dist/polyfills/stringFromCodePoint'>;
}
declare module 'emoji-mart/dist/svgs/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/svgs/index'>;
}
declare module 'emoji-mart/dist/utils/build-search.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/build-search'>;
}
declare module 'emoji-mart/dist/utils/emoji-index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/emoji-index'>;
}
declare module 'emoji-mart/dist/utils/emoji-indexSpec.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/emoji-indexSpec'>;
}
declare module 'emoji-mart/dist/utils/frequently.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/frequently'>;
}
declare module 'emoji-mart/dist/utils/index.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/index'>;
}
declare module 'emoji-mart/dist/utils/store.js' {
  declare module.exports: $Exports<'emoji-mart/dist/utils/store'>;
}
declare module 'emoji-mart/dist/vendor/raf-polyfill.js' {
  declare module.exports: $Exports<'emoji-mart/dist/vendor/raf-polyfill'>;
}
declare module 'emoji-mart/stories/index.js' {
  declare module.exports: $Exports<'emoji-mart/stories/index'>;
}
