// flow-typed signature: 878ebf4b5006d8d3fdce6b8b36fa696f
// flow-typed version: <<STUB>>/emoji-regex_v6.5.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-regex/es2015/index' {
  declare module.exports: any;
}

declare module 'emoji-regex/es2015/text' {
  declare module.exports: any;
}

declare module 'emoji-regex/text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-regex/es2015/index.js' {
  declare module.exports: $Exports<'emoji-regex/es2015/index'>;
}
declare module 'emoji-regex/es2015/text.js' {
  declare module.exports: $Exports<'emoji-regex/es2015/text'>;
}
declare module 'emoji-regex/index' {
  declare module.exports: $Exports<'emoji-regex'>;
}
declare module 'emoji-regex/index.js' {
  declare module.exports: $Exports<'emoji-regex'>;
}
declare module 'emoji-regex/text.js' {
  declare module.exports: $Exports<'emoji-regex/text'>;
}
