// flow-typed signature: cc60296b94a91297f376602773cf0e9a
// flow-typed version: <<STUB>>/emotion_v^5.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion/babel' {
  declare module.exports: any;
}

declare module 'emotion/dist/DO-NOT-USE.min' {
  declare module.exports: any;
}

declare module 'emotion/lib/attrs' {
  declare module.exports: any;
}

declare module 'emotion/lib/babel' {
  declare module.exports: any;
}

declare module 'emotion/lib/css-prop' {
  declare module.exports: any;
}

declare module 'emotion/lib/hash' {
  declare module.exports: any;
}

declare module 'emotion/lib/index' {
  declare module.exports: any;
}

declare module 'emotion/lib/inline' {
  declare module.exports: any;
}

declare module 'emotion/lib/loader' {
  declare module.exports: any;
}

declare module 'emotion/lib/parser' {
  declare module.exports: any;
}

declare module 'emotion/lib/react' {
  declare module.exports: any;
}

declare module 'emotion/lib/server' {
  declare module.exports: any;
}

declare module 'emotion/lib/sheet' {
  declare module.exports: any;
}

declare module 'emotion/lib/styled' {
  declare module.exports: any;
}

declare module 'emotion/lib/theme' {
  declare module.exports: any;
}

declare module 'emotion/lib/utils' {
  declare module.exports: any;
}

declare module 'emotion/lib/vue' {
  declare module.exports: any;
}

declare module 'emotion/react' {
  declare module.exports: any;
}

declare module 'emotion/server' {
  declare module.exports: any;
}

declare module 'emotion/src/attrs' {
  declare module.exports: any;
}

declare module 'emotion/src/babel' {
  declare module.exports: any;
}

declare module 'emotion/src/css-prop' {
  declare module.exports: any;
}

declare module 'emotion/src/hash' {
  declare module.exports: any;
}

declare module 'emotion/src/index' {
  declare module.exports: any;
}

declare module 'emotion/src/inline' {
  declare module.exports: any;
}

declare module 'emotion/src/parser' {
  declare module.exports: any;
}

declare module 'emotion/src/react' {
  declare module.exports: any;
}

declare module 'emotion/src/server' {
  declare module.exports: any;
}

declare module 'emotion/src/sheet' {
  declare module.exports: any;
}

declare module 'emotion/src/utils' {
  declare module.exports: any;
}

declare module 'emotion/src/vue' {
  declare module.exports: any;
}

declare module 'emotion/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion/babel.js' {
  declare module.exports: $Exports<'emotion/babel'>;
}
declare module 'emotion/dist/DO-NOT-USE.min.js' {
  declare module.exports: $Exports<'emotion/dist/DO-NOT-USE.min'>;
}
declare module 'emotion/lib/attrs.js' {
  declare module.exports: $Exports<'emotion/lib/attrs'>;
}
declare module 'emotion/lib/babel.js' {
  declare module.exports: $Exports<'emotion/lib/babel'>;
}
declare module 'emotion/lib/css-prop.js' {
  declare module.exports: $Exports<'emotion/lib/css-prop'>;
}
declare module 'emotion/lib/hash.js' {
  declare module.exports: $Exports<'emotion/lib/hash'>;
}
declare module 'emotion/lib/index.js' {
  declare module.exports: $Exports<'emotion/lib/index'>;
}
declare module 'emotion/lib/inline.js' {
  declare module.exports: $Exports<'emotion/lib/inline'>;
}
declare module 'emotion/lib/loader.js' {
  declare module.exports: $Exports<'emotion/lib/loader'>;
}
declare module 'emotion/lib/parser.js' {
  declare module.exports: $Exports<'emotion/lib/parser'>;
}
declare module 'emotion/lib/react.js' {
  declare module.exports: $Exports<'emotion/lib/react'>;
}
declare module 'emotion/lib/server.js' {
  declare module.exports: $Exports<'emotion/lib/server'>;
}
declare module 'emotion/lib/sheet.js' {
  declare module.exports: $Exports<'emotion/lib/sheet'>;
}
declare module 'emotion/lib/styled.js' {
  declare module.exports: $Exports<'emotion/lib/styled'>;
}
declare module 'emotion/lib/theme.js' {
  declare module.exports: $Exports<'emotion/lib/theme'>;
}
declare module 'emotion/lib/utils.js' {
  declare module.exports: $Exports<'emotion/lib/utils'>;
}
declare module 'emotion/lib/vue.js' {
  declare module.exports: $Exports<'emotion/lib/vue'>;
}
declare module 'emotion/react.js' {
  declare module.exports: $Exports<'emotion/react'>;
}
declare module 'emotion/server.js' {
  declare module.exports: $Exports<'emotion/server'>;
}
declare module 'emotion/src/attrs.js' {
  declare module.exports: $Exports<'emotion/src/attrs'>;
}
declare module 'emotion/src/babel.js' {
  declare module.exports: $Exports<'emotion/src/babel'>;
}
declare module 'emotion/src/css-prop.js' {
  declare module.exports: $Exports<'emotion/src/css-prop'>;
}
declare module 'emotion/src/hash.js' {
  declare module.exports: $Exports<'emotion/src/hash'>;
}
declare module 'emotion/src/index.js' {
  declare module.exports: $Exports<'emotion/src/index'>;
}
declare module 'emotion/src/inline.js' {
  declare module.exports: $Exports<'emotion/src/inline'>;
}
declare module 'emotion/src/parser.js' {
  declare module.exports: $Exports<'emotion/src/parser'>;
}
declare module 'emotion/src/react.js' {
  declare module.exports: $Exports<'emotion/src/react'>;
}
declare module 'emotion/src/server.js' {
  declare module.exports: $Exports<'emotion/src/server'>;
}
declare module 'emotion/src/sheet.js' {
  declare module.exports: $Exports<'emotion/src/sheet'>;
}
declare module 'emotion/src/utils.js' {
  declare module.exports: $Exports<'emotion/src/utils'>;
}
declare module 'emotion/src/vue.js' {
  declare module.exports: $Exports<'emotion/src/vue'>;
}
declare module 'emotion/vue.js' {
  declare module.exports: $Exports<'emotion/vue'>;
}
