// flow-typed signature: ae2cc67451204c8801d9d459d4a8fecf
// flow-typed version: <<STUB>>/namespace-css-loader_v0.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'namespace-css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'namespace-css-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'namespace-css-loader/index' {
  declare module.exports: $Exports<'namespace-css-loader'>;
}
declare module 'namespace-css-loader/index.js' {
  declare module.exports: $Exports<'namespace-css-loader'>;
}
