// flow-typed signature: 336ba4350dfd953fecfb70dc3eb32b7c
// flow-typed version: <<STUB>>/quiq-chat_v1.22.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quiq-chat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quiq-chat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'quiq-chat/build/quiq-chat' {
  declare module.exports: any;
}

declare module 'quiq-chat/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'quiq-chat/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'quiq-chat/jest.setup' {
  declare module.exports: any;
}

declare module 'quiq-chat/rollup.config' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__mocks__/globals' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__mocks__/logging' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__mocks__/quiqFetch' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__mocks__/stubbornFetch' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__tests__/globals.test' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__tests__/quiqFetch.test' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/__tests__/websockets.test' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/apiCalls' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/appConstants' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/globals' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/index' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/logging' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/quiqFetch' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/QuiqSockets/quiqSockets' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/QuiqSockets/StatusCodes' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/sentry' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/storage/__mocks__/index' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/storage/__tests__/storage.test' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/storage/contactPointNamespacePlugin' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/storage/index' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/storage/modifiedTimestampPlugin' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/stubbornFetch' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/types' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/Utils/__mocks__/utils' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/Utils/__tests__/utils.test' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/Utils/sentryLoglevelPlugin' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/Utils/utils' {
  declare module.exports: any;
}

declare module 'quiq-chat/src/websockets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'quiq-chat/build/quiq-chat.js' {
  declare module.exports: $Exports<'quiq-chat/build/quiq-chat'>;
}
declare module 'quiq-chat/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'quiq-chat/coverage/lcov-report/prettify'>;
}
declare module 'quiq-chat/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'quiq-chat/coverage/lcov-report/sorter'>;
}
declare module 'quiq-chat/jest.setup.js' {
  declare module.exports: $Exports<'quiq-chat/jest.setup'>;
}
declare module 'quiq-chat/rollup.config.js' {
  declare module.exports: $Exports<'quiq-chat/rollup.config'>;
}
declare module 'quiq-chat/src/__mocks__/globals.js' {
  declare module.exports: $Exports<'quiq-chat/src/__mocks__/globals'>;
}
declare module 'quiq-chat/src/__mocks__/logging.js' {
  declare module.exports: $Exports<'quiq-chat/src/__mocks__/logging'>;
}
declare module 'quiq-chat/src/__mocks__/quiqFetch.js' {
  declare module.exports: $Exports<'quiq-chat/src/__mocks__/quiqFetch'>;
}
declare module 'quiq-chat/src/__mocks__/stubbornFetch.js' {
  declare module.exports: $Exports<'quiq-chat/src/__mocks__/stubbornFetch'>;
}
declare module 'quiq-chat/src/__tests__/globals.test.js' {
  declare module.exports: $Exports<'quiq-chat/src/__tests__/globals.test'>;
}
declare module 'quiq-chat/src/__tests__/index.test.js' {
  declare module.exports: $Exports<'quiq-chat/src/__tests__/index.test'>;
}
declare module 'quiq-chat/src/__tests__/quiqFetch.test.js' {
  declare module.exports: $Exports<'quiq-chat/src/__tests__/quiqFetch.test'>;
}
declare module 'quiq-chat/src/__tests__/websockets.test.js' {
  declare module.exports: $Exports<'quiq-chat/src/__tests__/websockets.test'>;
}
declare module 'quiq-chat/src/apiCalls.js' {
  declare module.exports: $Exports<'quiq-chat/src/apiCalls'>;
}
declare module 'quiq-chat/src/appConstants.js' {
  declare module.exports: $Exports<'quiq-chat/src/appConstants'>;
}
declare module 'quiq-chat/src/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'quiq-chat/src/coverage/lcov-report/prettify'>;
}
declare module 'quiq-chat/src/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'quiq-chat/src/coverage/lcov-report/sorter'>;
}
declare module 'quiq-chat/src/globals.js' {
  declare module.exports: $Exports<'quiq-chat/src/globals'>;
}
declare module 'quiq-chat/src/index.js' {
  declare module.exports: $Exports<'quiq-chat/src/index'>;
}
declare module 'quiq-chat/src/logging.js' {
  declare module.exports: $Exports<'quiq-chat/src/logging'>;
}
declare module 'quiq-chat/src/quiqFetch.js' {
  declare module.exports: $Exports<'quiq-chat/src/quiqFetch'>;
}
declare module 'quiq-chat/src/QuiqSockets/quiqSockets.js' {
  declare module.exports: $Exports<'quiq-chat/src/QuiqSockets/quiqSockets'>;
}
declare module 'quiq-chat/src/QuiqSockets/StatusCodes.js' {
  declare module.exports: $Exports<'quiq-chat/src/QuiqSockets/StatusCodes'>;
}
declare module 'quiq-chat/src/sentry.js' {
  declare module.exports: $Exports<'quiq-chat/src/sentry'>;
}
declare module 'quiq-chat/src/storage/__mocks__/index.js' {
  declare module.exports: $Exports<'quiq-chat/src/storage/__mocks__/index'>;
}
declare module 'quiq-chat/src/storage/__tests__/storage.test.js' {
  declare module.exports: $Exports<'quiq-chat/src/storage/__tests__/storage.test'>;
}
declare module 'quiq-chat/src/storage/contactPointNamespacePlugin.js' {
  declare module.exports: $Exports<'quiq-chat/src/storage/contactPointNamespacePlugin'>;
}
declare module 'quiq-chat/src/storage/index.js' {
  declare module.exports: $Exports<'quiq-chat/src/storage/index'>;
}
declare module 'quiq-chat/src/storage/modifiedTimestampPlugin.js' {
  declare module.exports: $Exports<'quiq-chat/src/storage/modifiedTimestampPlugin'>;
}
declare module 'quiq-chat/src/stubbornFetch.js' {
  declare module.exports: $Exports<'quiq-chat/src/stubbornFetch'>;
}
declare module 'quiq-chat/src/types.js' {
  declare module.exports: $Exports<'quiq-chat/src/types'>;
}
declare module 'quiq-chat/src/Utils/__mocks__/utils.js' {
  declare module.exports: $Exports<'quiq-chat/src/Utils/__mocks__/utils'>;
}
declare module 'quiq-chat/src/Utils/__tests__/utils.test.js' {
  declare module.exports: $Exports<'quiq-chat/src/Utils/__tests__/utils.test'>;
}
declare module 'quiq-chat/src/Utils/sentryLoglevelPlugin.js' {
  declare module.exports: $Exports<'quiq-chat/src/Utils/sentryLoglevelPlugin'>;
}
declare module 'quiq-chat/src/Utils/utils.js' {
  declare module.exports: $Exports<'quiq-chat/src/Utils/utils'>;
}
declare module 'quiq-chat/src/websockets.js' {
  declare module.exports: $Exports<'quiq-chat/src/websockets'>;
}
