// flow-typed signature: 6a96f6f4e045c73efd718935a1c30eff
// flow-typed version: <<STUB>>/react-textarea-autosize_v4.0.5/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textarea-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-textarea-autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-textarea-autosize/lib/calculateNodeHeight' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/lib/TextareaAutosize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-textarea-autosize/lib/calculateNodeHeight.js' {
  declare module.exports: $Exports<'react-textarea-autosize/lib/calculateNodeHeight'>;
}
declare module 'react-textarea-autosize/lib/TextareaAutosize.js' {
  declare module.exports: $Exports<'react-textarea-autosize/lib/TextareaAutosize'>;
}
