// flow-typed signature: 69f35bd4e842ead5b62b89c834d3beca
// flow-typed version: <<STUB>>/react-easy-emoji_v1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-easy-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-easy-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-easy-emoji/lib/makeTwemojiRenderer' {
  declare module.exports: any;
}

declare module 'react-easy-emoji/lib/replaceEmoji' {
  declare module.exports: any;
}

declare module 'react-easy-emoji/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-easy-emoji/index' {
  declare module.exports: $Exports<'react-easy-emoji'>;
}
declare module 'react-easy-emoji/index.js' {
  declare module.exports: $Exports<'react-easy-emoji'>;
}
declare module 'react-easy-emoji/lib/makeTwemojiRenderer.js' {
  declare module.exports: $Exports<'react-easy-emoji/lib/makeTwemojiRenderer'>;
}
declare module 'react-easy-emoji/lib/replaceEmoji.js' {
  declare module.exports: $Exports<'react-easy-emoji/lib/replaceEmoji'>;
}
declare module 'react-easy-emoji/test/test.js' {
  declare module.exports: $Exports<'react-easy-emoji/test/test'>;
}
