// flow-typed signature: 65398d340836006a29103c2b5c7ac9a5
// flow-typed version: <<STUB>>/react-click-outside-component_v1.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-click-outside-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-click-outside-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-click-outside-component/build/index' {
  declare module.exports: any;
}

declare module 'react-click-outside-component/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-click-outside-component/build/index.js' {
  declare module.exports: $Exports<'react-click-outside-component/build/index'>;
}
declare module 'react-click-outside-component/example/index.js' {
  declare module.exports: $Exports<'react-click-outside-component/example/index'>;
}
declare module 'react-click-outside-component/index' {
  declare module.exports: $Exports<'react-click-outside-component'>;
}
declare module 'react-click-outside-component/index.js' {
  declare module.exports: $Exports<'react-click-outside-component'>;
}
