// flow-typed signature: 7332390d5a6fe6536c3e113ee3854044
// flow-typed version: <<STUB>>/redux-store-watch_v0.0.11/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-store-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-store-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-store-watch/index' {
  declare module.exports: $Exports<'redux-store-watch'>;
}
declare module 'redux-store-watch/index.js' {
  declare module.exports: $Exports<'redux-store-watch'>;
}
