/* eslint-disable global-require */
module.exports = {
  envelope: require('@fortawesome/fontawesome-pro-solid/faEnvelope'),
  fileArchive: require('@fortawesome/fontawesome-pro-regular/faFileArchive'),
  fileAudio: require('@fortawesome/fontawesome-pro-regular/faFileAudio'),
  fileExcel: require('@fortawesome/fontawesome-pro-regular/faFileExcel'),
  filePdf: require('@fortawesome/fontawesome-pro-regular/faFilePdf'),
  filePowerpoint: require('@fortawesome/fontawesome-pro-regular/faFilePowerpoint'),
  fileVideo: require('@fortawesome/fontawesome-pro-regular/faFileVideo'),
  fileWord: require('@fortawesome/fontawesome-pro-regular/faFileWord'),
  times: require('@fortawesome/fontawesome-pro-regular/faTimes'),
  volumeOff: require('@fortawesome/fontawesome-pro-solid/faVolumeOff'),
  volumeUp: require('@fortawesome/fontawesome-pro-solid/faVolumeUp'),
  /**
   * Core Icons
   */
  ban: require('core-ui/coreIcons').ban,
  bars: require('core-ui/coreIcons').bars,
  bolt: require('core-ui/coreIcons').bolt,
  calendar: require('core-ui/coreIcons').calendar,
  camera: require('core-ui/coreIcons').camera,
  chartLine: require('core-ui/coreIcons').chartLine,
  check: require('core-ui/coreIcons').check,
  checkCircleFilled: require('core-ui/coreIcons').checkCircleFilled,
  clipboard: require('core-ui/coreIcons').clipboard,
  clock: require('core-ui/coreIcons').clock,
  cloudDownload: require('core-ui/coreIcons').cloudDownload,
  cog: require('core-ui/coreIcons').cog,
  comments: require('core-ui/coreIcons').comments,
  connectdevelop: require('core-ui/coreIcons').connectdevelop,
  cubes: require('core-ui/coreIcons').cubes,
  ellipsisH: require('core-ui/coreIcons').ellipsisH,
  ellipsisV: require('core-ui/coreIcons').ellipsisV,
  exchange: require('core-ui/coreIcons').exchange,
  facebookSquare: require('core-ui/coreIcons').facebookSquare,
  file: require('core-ui/coreIcons').file,
  fire: require('core-ui/coreIcons').fire,
  gift: require('core-ui/coreIcons').gift,
  globe: require('core-ui/coreIcons').globe,
  google: require('core-ui/coreIcons').google,
  heart: require('core-ui/coreIcons').heart,
  inbox: require('core-ui/coreIcons').inbox,
  infoCircle: require('core-ui/coreIcons').infoCircle,
  key: require('core-ui/coreIcons').key,
  list: require('core-ui/coreIcons').list,
  mobile: require('core-ui/coreIcons').mobile,
  paperclip: require('core-ui/coreIcons').paperclip,
  paperPlane: require('core-ui/coreIcons').paperPlane,
  paste: require('core-ui/coreIcons').paste,
  pencil: require('core-ui/coreIcons').pencil,
  question: require('core-ui/coreIcons').question,
  questionCircle: require('core-ui/coreIcons').questionCircle,
  reply: require('core-ui/coreIcons').reply,
  retweet: require('core-ui/coreIcons').retweet,
  search: require('core-ui/coreIcons').search,
  sitemap: require('core-ui/coreIcons').sitemap,
  smile: require('core-ui/coreIcons').smile,
  timesCircle: require('core-ui/coreIcons').timesCircle,
  trash: require('core-ui/coreIcons').trash,
  upload: require('core-ui/coreIcons').upload,
  user: require('core-ui/coreIcons').user,
  userPlus: require('core-ui/coreIcons').userPlus,
  users: require('core-ui/coreIcons').users,
  video: require('core-ui/coreIcons').video,
  wrench: require('core-ui/coreIcons').wrench,
};
/* eslint-disable global-require */
