export default {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  position: 'fixed',
  boxSizing: 'border-box',
  bottom: '24px',
  right: '24px',
  width: '60px',
  height: '60px',
  border: 'none',
  borderRadius: '100%',
  color: '#fff',
  fill: '#fff',
  cursor: 'pointer',
  transition: '0.15s ease-in-out all',
  boxShadow: 'rgba(0, 0, 0, 0.117647) 0px 1px 6px, rgba(0, 0, 0, 0.11 7647) 0px 1px 4px',
};
