export const registerChatClient = jest.fn();
export const getChatClient = jest.fn().mockReturnValue({
  onNewMessages: jest.fn().mockReturnThis(),
  onRegistration: jest.fn().mockReturnThis(),
  onAgentTyping: jest.fn().mockReturnThis(),
  onError: jest.fn().mockReturnThis(),
  onErrorResolved: jest.fn().mockReturnThis(),
  onConnectionStatusChange: jest.fn().mockReturnThis(),
  onNewSession: jest.fn().mockReturnThis(),
  onBurn: jest.fn().mockReturnThis(),
  onClientInactiveTimeout: jest.fn().mockReturnThis(),
  start: jest.fn(),
  stop: jest.fn(),
  emailTranscript: jest.fn(),
  getMessages: jest.fn(),
  joinChat: jest.fn(),
  leaveChat: jest.fn(),
  sendTextMessage: jest.fn(),
  updateMessagePreview: jest.fn(),
  sendRegistration: jest.fn(),
  checkForAgents: jest.fn(),
  hasTakenMeaningfulAction: jest.fn(),
  isRegistered: jest.fn().mockReturnValue(false),
  isChatVisible: jest.fn(),
  getChatConfiguration: jest.fn(),
  onSendTranscript: jest.fn().mockReturnValue({
    id: 1,
    type: 'SendTranscript',
    timestamp: 123456,
  }),
});
